In [3]:
import numpy as np
import pandas as pd
from matplotlib import pyplot
import sklearn



In [3]:
print(np.__version__)

1.20.1


In [4]:
print(pd.__version__)

1.2.4


In [2]:
import numpy as np
print(np.__version__)

1.20.1


In [3]:
a=np.array([1,2,3,4,5])

In [4]:
print(a)

[1 2 3 4 5]


In [5]:
a

array([1, 2, 3, 4, 5])

In [7]:
b= np.array([(1.5,2,3),(4,5,6)],dtype=float)

In [8]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [9]:
b.ndim

2

In [10]:
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

In [11]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [12]:
c.ndim

3

In [14]:
z=np.zeros((4,4))

In [15]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
o=np.ones((3,4))

In [17]:
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
v=np.arange(0,10).reshape(5,2)

In [19]:
v

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
g=np.linspace(1,10,5)

In [23]:
g

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
L=np.eye(3)

In [25]:
L

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
r=np.random.rand(3,3)
r

array([[0.86096631, 0.74596285, 0.02919195],
       [0.88871292, 0.80233632, 0.90479189],
       [0.58040887, 0.58002083, 0.99717525]])

In [29]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [30]:
b.shape

(2, 3)

In [31]:
a

array([1, 2, 3, 4, 5])

In [32]:
len(a)

5

In [33]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [34]:
c.dtype

dtype('float64')

In [35]:
t=c.astype(int)
t

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [4, 5, 6]]])

In [39]:
print(a)
print(a.sum())
print(a.min())

[1 2 3 4 5]
15
1


In [44]:
print(b)
print(b.max(axis=1))

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[3. 6.]


In [45]:
print(a.mean())

3.0


In [46]:
np.median(a)

3.0

In [47]:
np.mean(a)

3.0

In [48]:
p=np.array([4,2,1,6,8,3,7])
print(p)

[4 2 1 6 8 3 7]


In [50]:
y=(p.sort())

In [52]:
p.sort()

In [53]:
p

array([1, 2, 3, 4, 6, 7, 8])

In [54]:
p[0:]

array([1, 2, 3, 4, 6, 7, 8])

In [55]:
p[0:4]

array([1, 2, 3, 4])

In [56]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [57]:
b[0:2,1]

array([2., 5.])

In [58]:
k=np.transpose(b)

In [59]:
k

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [60]:
k.reshape(6,1)

array([[1.5],
       [4. ],
       [2. ],
       [5. ],
       [3. ],
       [6. ]])

In [61]:
k.reshape(1,6)

array([[1.5, 4. , 2. , 5. , 3. , 6. ]])

In [62]:
k

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [63]:
v=np.ravel(k)

In [64]:
v

array([1.5, 4. , 2. , 5. , 3. , 6. ])

In [65]:
v.ndim

1

In [66]:
v.shape

(6,)

In [78]:
f=v.reshape(6,1)
print(f)

[[1.5]
 [4. ]
 [2. ]
 [5. ]
 [3. ]
 [6. ]]


In [68]:
f

array([[1.5, 4. , 2. ],
       [5. , 3. , 6. ]])

In [86]:
h=np.array([(0,1),(3,4),(1,4),(5,6),(6,7),(66,12)],dtype=float)
f.ndim
h.ndim

2

In [87]:
m=np.hstack((f,h))
print(m)

[[ 1.5  0.   1. ]
 [ 4.   3.   4. ]
 [ 2.   1.   4. ]
 [ 5.   5.   6. ]
 [ 3.   6.   7. ]
 [ 6.  66.  12. ]]


In [89]:
n=np.vstack((f,h))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 2