In [4]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [5]:

df = pd.read_csv('C:/Users/User/Desktop/ml Assi/diabetes.csv')

In [6]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
X=df.iloc[:,0:8]
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [8]:
y=df.Outcome

In [9]:
print('X shape :',X.shape)
print('y shape :',y.shape)

X shape : (768, 8)
y shape : (768,)


In [10]:
#standardization
scaler = StandardScaler()
X_std = scaler.fit_transform(X)


In [11]:
X_train,X_test,y_train,y_test=train_test_split(X_std,y,test_size=0.3,random_state=0)

In [12]:
print('X_train shape',X_train.shape)
print('y_train shape',y_train.shape)

print()
print('X_test shape',X_test.shape)
print('y_test= shape',y_test.shape)

X_train shape (537, 8)
y_train shape (537,)

X_test shape (231, 8)
y_test= shape (231,)


In [13]:
mlp=MLPClassifier(hidden_layer_sizes=(50),activation='relu',max_iter=200,verbose=True)
mlp

MLPClassifier(hidden_layer_sizes=50, verbose=True)

In [14]:
mlp.fit(X_train,y_train)

Iteration 1, loss = 0.77230937
Iteration 2, loss = 0.75485031
Iteration 3, loss = 0.73831102
Iteration 4, loss = 0.72304479
Iteration 5, loss = 0.70918175
Iteration 6, loss = 0.69531059
Iteration 7, loss = 0.68291283
Iteration 8, loss = 0.67081971
Iteration 9, loss = 0.65977596
Iteration 10, loss = 0.64884331
Iteration 11, loss = 0.63887650
Iteration 12, loss = 0.62944091
Iteration 13, loss = 0.62030336
Iteration 14, loss = 0.61205187
Iteration 15, loss = 0.60378220
Iteration 16, loss = 0.59625691
Iteration 17, loss = 0.58888177
Iteration 18, loss = 0.58173458
Iteration 19, loss = 0.57515732
Iteration 20, loss = 0.56874075
Iteration 21, loss = 0.56284101
Iteration 22, loss = 0.55673713
Iteration 23, loss = 0.55125975
Iteration 24, loss = 0.54601816
Iteration 25, loss = 0.54093568
Iteration 26, loss = 0.53618374
Iteration 27, loss = 0.53159204
Iteration 28, loss = 0.52718109
Iteration 29, loss = 0.52300581
Iteration 30, loss = 0.51920654
Iteration 31, loss = 0.51530399
Iteration 32, los

C:\Users\User\anaconda3\envs\mlcl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=50, verbose=True)

In [15]:
print(mlp.score(X_train,y_train)*100)

81.3780260707635


In [16]:
print(mlp.score(X_test,y_test)*100)

77.05627705627705


In [17]:
y_pred=mlp.predict(X_test)
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [18]:
y_test.ravel()

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [19]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[135  22]
 [ 31  43]]


In [20]:
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.81      0.86      0.84       157
           1       0.66      0.58      0.62        74

    accuracy                           0.77       231
   macro avg       0.74      0.72      0.73       231
weighted avg       0.76      0.77      0.77       231



In [21]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [22]:
sample=np.array([5,121,72,23,112,26.2,0.245,30])
print('Shape of sample:',sample.shape)
print('Shape of X_test:',X_test.shape)

Shape of sample: (8,)
Shape of X_test: (231, 8)


In [23]:
sample=np.expand_dims(sample,0)
print('Shape of sample:',sample.shape)

Shape of sample: (1, 8)


In [24]:
mlp.predict(sample)

array([1], dtype=int64)