In [1]:


import numpy as np
import pandas as pd

from sklearn import preprocessing,datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler,Normalizer,LabelEncoder


In [8]:
X = np.random.random((10,5))

In [9]:
X

array([[0.60481675, 0.39797483, 0.24091921, 0.30931902, 0.3207316 ],
       [0.84545861, 0.21360624, 0.2459888 , 0.03015406, 0.59655656],
       [0.18065889, 0.98155773, 0.69182144, 0.44295654, 0.47632224],
       [0.49085039, 0.57866613, 0.17606308, 0.94600707, 0.7823973 ],
       [0.25613993, 0.67742899, 0.68659856, 0.35930381, 0.2536781 ],
       [0.40094393, 0.00733579, 0.65346938, 0.38713954, 0.29778431],
       [0.51644532, 0.05141262, 0.35271057, 0.1258673 , 0.80854534],
       [0.46342229, 0.51702829, 0.69609509, 0.81419557, 0.09027597],
       [0.70050258, 0.95354671, 0.51434973, 0.25854769, 0.06432145],
       [0.39535428, 0.37663329, 0.15302514, 0.75344902, 0.22218214]])

In [6]:
y=np.array(['M','M','F','F','M','F','M','M','F','F'])

In [7]:
print(x.shape)
print(y.shape)

(10, 5)
(10,)


In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [10]:

import numpy as np
import pandas as pd

from sklearn import preprocessing,datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.preprocessing import StandardScaler,Normalizer,LabelEncoder

#Dataset Creation
X = np.random.random((10,5))
print(X)

y=np.array(['M','M','F','F','M','F','M','M','F','F'])

print(X.shape)
print(y.shape)

X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.3,random_state=0)


#preprocessing
# 1.Standardization

scaler= StandardScaler()  #object of StandardScaler

Xtrain_std=scaler.fit_transform(X_train)
Xtest_std=scaler.transform(X_test)

print(Xtrain_std.mean(),Xtrain_std.std())

from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()   #obj of labelEncoder

y_enc=enc.fit_transform(Y_train)
yt_enc=enc.fit_transform(Y_test)
print(y)
print(y_enc)

#Supervised Learning
#1.Linear Regression
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC,SVR
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier,MLPRegressor


#Unsupervised 
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA


#model fitting
mlp = MLPClassifier()
print(mlp)
y_enc
print(Xtrain_std.shape,y_enc.shape)
mlp.fit(Xtrain_std,y_enc)


print(mlp.score(Xtrain_std,y_enc))
print(mlp.score(Xtest_std,yt_enc))

y_pred=mlp.predict(X_test)
print(y_pred)

cm=confusion_matrix(yt_enc,y_pred)
print(cm)

from sklearn.metrics import classification_report
cr = classification_report(yt_enc, y_pred)
print(cr)

[[0.37447858 0.41533535 0.01026744 0.86689279 0.00459985]
 [0.90589759 0.24260631 0.48245941 0.44665253 0.88011908]
 [0.00945873 0.62768784 0.643484   0.19825605 0.24258206]
 [0.20077217 0.15549231 0.43022923 0.96162193 0.54566386]
 [0.23009949 0.27816963 0.38184111 0.63248919 0.44335375]
 [0.33636986 0.78541845 0.20298847 0.08188214 0.25247758]
 [0.01605069 0.15354915 0.0493207  0.98150704 0.71345353]
 [0.21684354 0.38367447 0.19276196 0.7995327  0.69577043]
 [0.63745015 0.13255629 0.04432065 0.47975982 0.48300442]
 [0.3659691  0.73225565 0.411531   0.2604324  0.98620432]]
(10, 5)
(10,)
8.881784197001253e-17 1.0
['M' 'M' 'F' 'F' 'M' 'F' 'M' 'M' 'F' 'F']
[0 1 1 1 0 1 0]
MLPClassifier()
(7, 5) (7,)
1.0
0.3333333333333333
[0 1 1]
[[1 1]
 [0 1]]
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.50      1.00      0.67         1

    accuracy                           0.67         3
   macro avg       0.75      

C:\Users\User\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
